# Generated by Django 4.2.4 on 2024-12-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('hint_cost', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(default=10)),
                ('task_type', models.CharField(choices=[('riddle', 'Загадка'), ('puzzle', 'Ребус'), ('poem', 'Стих')], max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bot.location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('coins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='bot.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_locations', to='bot.user')),
            ],
            options={
                'unique_together': {('user', 'location')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_current_location', to='bot.userquestlocation'),
        ),
        migrations.AddField(
            model_name='user',
            name='solved_tasks',
            field=models.ManyToManyField(blank=True, related_name='solvers', to='bot.task'),
        ),
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riddle', to='bot.task')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='puzzles/')),
                ('instructions', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to='bot.task')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poem', to='bot.task')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('hint_type', models.CharField(choices=[('riddle', 'Загадка'), ('puzzle', 'Ребус')], max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='bot.task')),
            ],
        ),
    ]
