# Generated by Django 4.2.4 on 2024-12-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_scenario_scenariostep_hint_image_riddle_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='poem',
            name='task',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='task',
        ),
        migrations.RemoveField(
            model_name='riddle',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='userquestlocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userquestlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userquestlocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userscenarioprogress',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='userscenarioprogress',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='userscenarioprogress',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='scenariostep',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
        migrations.RemoveField(
            model_name='scenariostep',
            name='task',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='solved_tasks',
        ),
        migrations.AddField(
            model_name='scenario',
            name='locations',
            field=models.ManyToManyField(related_name='scenarios', through='bot.ScenarioStep', to='bot.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/'),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='bot.scenario'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('riddle', 'Загадка'), ('puzzle', 'Ребус'), ('poem', 'Стих'), ('message', 'Сообщение')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
        migrations.DeleteModel(
            name='Poem',
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
        migrations.DeleteModel(
            name='Riddle',
        ),
        migrations.DeleteModel(
            name='UserQuestLocation',
        ),
        migrations.DeleteModel(
            name='UserScenarioProgress',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_progress', to='bot.scenariostep'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='bot.scenario'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='bot.user'),
        ),
    ]
